package eplccode

import (
	"encoding/json"
	"eplc/src/libepl/eplparse/symboltable"
	"fmt"
	"os"
	"strings"
)

func CreateLabel(index uint, text string) Label {
	return Label{index, text}
}
type Label struct {
	index uint
	text string
}
func (l *Label) asString() string {
	return fmt.Sprintf("L%d: %s\n", l.index, l.text)
}

type Writer struct {
	Fname string
	targetFile *os.File
	TargetName string
	Labels []Label
}

func (w *Writer) InitializeWriter() {
	w.TargetName = strings.Split(w.Fname, ".")[0]+".bin"
	 file, _ := os.Create(w.TargetName)
	_, _ = file.WriteString("#Generated by epl compiler\n")
	 w.targetFile = file
}

func (w *Writer) WriteToTarget() {
	for _, lb := range w.Labels {
		_, _ = w.targetFile.WriteString(lb.asString())
	}
}

func (w *Writer) UpdateLabels(labels []Label) {
	for _, lb := range labels{
		w.Labels = append(w.Labels, lb)
	}
}


func (w *Writer) UpdateLabel(label Label) {
	w.Labels = append(w.Labels, label)
}

func (w *Writer) produceST(st symboltable.SymbolTable) {
	b, err := json.Marshal(st)

	if (err != nil) {

	} else {
		file, _ := os.Create("SymbolTable.json")
		_, _ = file.Write(b)
	}
}