package Types

var (
	TypeUint    BasicType = NewMathematicalBasicType("uint")
	TypeUint8   BasicType = NewMathematicalBasicType("uint8")
	TypeUint16  BasicType = NewMathematicalBasicType("uint16")
	TypeUint32  BasicType = NewMathematicalBasicType("uint32")
	TypeUint64  BasicType = NewMathematicalBasicType("uint64")
	TypeInt     BasicType = NewMathematicalBasicType("int")
	TypeInt8    BasicType = NewMathematicalBasicType("int8")
	TypeInt16   BasicType = NewMathematicalBasicType("int16")
	TypeInt32   BasicType = NewMathematicalBasicType("int32")
	TypeInt64   BasicType = NewMathematicalBasicType("int64")
	TypeFloat   BasicType = NewMathematicalBasicType("float")
	TypeFloat8  BasicType = NewMathematicalBasicType("float8")
	TypeFloat16 BasicType = NewMathematicalBasicType("float16")
	TypeFloat32 BasicType = NewMathematicalBasicType("float32")
	TypeFloat64 BasicType = NewMathematicalBasicType("float64")
	TypeCmx     BasicType = NewMathematicalBasicType("cmx")
	TypeCmx64   BasicType = NewMathematicalBasicType("cmx64")
	TypeString  BasicType = NewBasicType("string")
	TypeBool    BasicType = NewBasicType("bool")
)
